In [17]:
import numpy as np

In [18]:
space=np.linspace(1,10,12) 
space

array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

In [19]:
ais= space.astype(int)

In [20]:
ais

array([ 1,  1,  2,  3,  4,  5,  5,  6,  7,  8,  9, 10])

In [21]:
space[2]=1

In [22]:
space

array([ 1.        ,  1.81818182,  1.        ,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

In [23]:
ww=space.sum()

In [24]:
ww

64.36363636363637

In [25]:
sw=np.array([[1,4,8],[6,5,4],[5,2,8]])

In [26]:
sw[1][0]

6

In [27]:
aq=([1,4,5,9,8,5,2,36,5])

In [28]:
aq.sort()


In [29]:
aq

[1, 2, 4, 5, 5, 5, 8, 9, 36]

In [30]:
sq2=np.array([[1,5,8],[6,51,4],[51,2,8]])

In [31]:
sw+sq2

array([[ 2,  9, 16],
       [12, 56,  8],
       [56,  4, 16]])